# Generated by Django 4.2.7 on 2023-11-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
