# Generated by Django 4.2.7 on 2023-11-27 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventory', '0002_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
